<?php

/* @var $this yii\web\View */
use yii\helpers\Url;
$this->title = 'demblock';
?>

<div class="section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
              <b>  <h3 class="text-center">TERMS OF USE and PRIVACY POLICY</h3></b>
            </div>
        </div>
    </div>
</div><br>
<div class="section text-ju2stify">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
            <br><br>

<br>
These Terms of Use describe the terms and conditions applicable to your access and use of of our marketplace ( “Site”).  This document is a legally binding agreement between you as the user(s) of the Site (referred to as “you”, “your” or “User” hereinafter) and our marketplace (referred to as “we”, “our” hereinafter).
<br><br>
Your use of our marketplace and its services, software and products (collectively the as the “Services” hereinafter) is subject to the terms and conditions contained in this document. This document and such other rules and policies of our marketplace are collectively referred to below as the “Terms”.  By accessing our marketplace you agree to accept and be bound by the Terms.  Please do not use our marketplace if you do not accept all of the Terms.  
You may be required to enter into a separate agreement, whether online or offline, with our marketplace (“Additional Agreements”).  If there is any conflict or inconsistency between the Terms and an Additional Agreement, the Additional Agreement shall take precedence over the Terms only in relation to that Service concerned.   
<br><br>
You may not use the Services and may not accept the Terms if (a) you are not of legal age to form a binding contract with our marketplace or (b) you are not permitted to receive any Services under the laws of other countries / regions including the country / region in which you are resident or from which you use the Services.
Our marketplace may amend any Terms at any time by posting the relevant amended and restated Term.   By continuing to use the Services or our marketplace, you agree that the amended Terms will apply to you. You must register as a member on our marketplace in order to access and use some Services. Services (or any features within the Services) may vary for different regions and countries. No warranty or representation is given that a particular Service or feature or function thereof or the same type and extent of the Service or features and functions thereof will be available for Users. 
<br><br>
Intellectual Property: Our marketplace is the sole owner or lawful licensee of all the rights and interests in our marketplace and the Site Content. Our marketplace and Site Content embody trade secrets and other intellectual property rights protected under worldwide copyright and other laws. All title, ownership and intellectual property rights in our marketplace and Site Content shall remain with Our marketplace, our affiliates or licensors of the Site Content, as the case may be. All rights not otherwise claimed under the Terms or by Our marketplace are hereby reserved.
<br><br>
User must be registered on our marketplace to access or use some Services (a registered User is also referred to as a “Member” below). Except with our marketplace’s approval, one User may only register one member account on our marketplace. Our marketplace may cancel or terminate a User’s member account if our marketplace has reasons to suspect that the User has concurrently registered or controlled two or more member accounts. Further, our marketplace may reject User’s application for registration for any reason in our sole discretion. Member agrees to notify our marketplace immediately if thez become aware of any unauthorized use of your password or your account or any other breach of security of your account.
<br><br>
Each Member agrees to indemnify Our marketplace, our affiliates, directors, employees, agents and representatives and to hold them harmless, from any and all damages, losses, claims and liabilities (including legal costs on a full indemnity basis) which may arise from your submission, posting or display of any User Content, from your use of our marketplace or Services, or from your breach of the Terms.
 <br><br>
As a condition of your access to and use of our marketplace or Services, you agree that you will comply with all applicable laws and regulations when using our marketplace or Services.
Our marketplace may allow Users to access to content, products or services offered by third parties through hyperlinks. You are cautioned to read such web our marketplace' terms and conditions and/or privacy policies before using our marketplace. You acknowledge that our marketplace has no control over such third parties' web our marketplace, does not monitor such web our marketplace, and shall not be responsible or liable to anyone for such web our marketplace, or any content, products or services made available on such web our marketplace.<br><br>
By posting or displaying any information, content or material (“User Content”) on our marketplace or providing any User Content to us  or our representative(s), and to the extent permitted under applicable laws, you grant an irrevocable, perpetual, worldwide, royalty-free, and sub-licensable (through multiple tiers) license to our marketplace to display, transmit, distribute, reproduce, publish, duplicate, adapt, modify, translate, create derivative works, and otherwise use any or all of the User Content in any form, media, or technology now known or not currently known in any manner and for any purpose which may be beneficial to the operation of our marketplace, the provision of any Services and/or the business of the User. You confirm and warrant to our marketplace that you have all the rights, power and authority necessary to grant the above license. Information that is protected under data protection laws will only be used and kept in compliance with those laws.<br><br>

Members agree that all activities that occur under your account (including without limitation, posting any company or product information, clicking to accept any Additional Agreements or rules, subscribing to or making any payment for any services,) will be deemed to have been authorized by the Member. Member acknowledges that sharing of your account with other persons, or allowing multiple users outside of your business entity to use your account (collectively, "multiple use"), may cause irreparable harm to Our marketplace or other Users of our marketplace. Member shall indemnify Our marketplace, our affiliates, directors, employees, agents and representatives against any loss or damages (including but not limited to loss of profits) suffered as a result of the multiple use of your account. Members also agree that in case of the multiple use of your account or Member’s failure to maintain the security of your account, Our marketplace shall not be liable for any loss or damages arising from such a breach and shall have the right to suspend or terminate Member’s account without liability to Member.<br><br>
Each Member represents, warrants and agrees that  1. you have full power and authority to accept the Terms, to grant the license and authorization and to perform the obligations hereunder; 2. you use our marketplace and Services for business purposes only; and 3. the address you provide when registering is the principal place of business of your business entity.  For purposes of this provision, a branch or liaison office will not be considered a separate entity and your principal place of business will be deemed to be that of your head office. <br><br>
 
Member will be required to provide information or material about your entity, business or products/services as part of the registration process on our marketplace or your use of any Service or the member account.  Each Member represents, warrants and agrees that 1. such information and material whether submitted during the registration process or thereafter throughout the continuation of the use of our marketplace or Service is true, accurate, current and complete, and 2. you will maintain and promptly amend all information and material to keep it true, accurate, current and complete.<br><br>
 
Each Member represents, warrants and agrees that 1. you shall be solely responsible for obtaining all necessary third party licenses and permissions regarding any User Content that you submit, post or display; 2. any User Content that you submit, post or display does not infringe or violate any of the copyright, patent, trademark, trade name, trade secrets or any other personal or proprietary rights of any third party (“Third Party Rights”); 3. you have the right and authority to sell, trade, distribute or export or offer to sell, trade, distribute or export the products or services described in the User Content and such sale, trade, distribution or export or offer does not violate any Third Party Rights and 4. you and your affiliates are not the subject of any trade restrictions, sanctions or other legal restrictions enacted by any country, international organization or jurisdiction.<br><br>

Each Member further represents, warrants and agrees that the User Content that you submit, post or display shall: be true, accurate, complete and lawful; not be false, misleading or deceptive; not contain information that is defamatory, libelous, threatening or harassing, obscene, objectionable, offensive, sexually explicit or harmful to minors; not contain information that is discriminatory or promotes discrimination based on race, sex, religion, nationality, disability, sexual orientation or age; not violate the Product Listing Policy, other Terms or any applicable Additional Agreements not violate any applicable laws and regulations (including without limitation those governing export control, consumer protection, unfair competition, or false advertising) or promote any activities which may violate any applicable laws and regulations; not contain any link directly or indirectly to any other web Our marketplace which includes any content that may violate the Terms. Member acknowledges and agrees that the Services may only be used by businesses and their representatives for business use and not for individual consumers or for personal use.<br><br>

Each Member further represents, warrants and agrees that you shall/are: carry on your activities on our marketplace in compliance with any applicable laws and regulations;conduct your business trades with other users of our marketplace in good faith; carry on your activities in accordance with the Terms and any applicable Additional Agreements; not use the Services or Our marketplace to defraud any person or entity (including without limitation sale of stolen items, use of stolen credit/debit cards); not impersonate any person or entity, misrepresent yourself or your affiliation with any person or entity; not engage in spamming or phishing; not engage in any other unlawful activities (including without limitation those which would constitute a criminal offence, give rise to civil liability,  etc) or encourage or abet any unlawful activities; not involve attempts to copy, reproduce, exploit or expropriate Our marketplace’s various proprietary directories, databases and listings; not involve any computer viruses or other destructive devices and codes that have the effect of damaging, interfering with, intercepting or expropriating any software or hardware system, data or personal information; not involve any scheme to undermine the integrity of the data, systems or networks used by Our marketplace and/or any user of our marketplace or gain unauthorized access to such data, systems or networks; not, and your director(s), officer(s), controlling party/ies, affiliates and legal jurisdiction in which any of the foregoing persons or entities is organized or has operations are not, persons or entities that are subject to any economic or fraud sanctions of any governmental, international or regulatory entities; and not engage in any activities that would otherwise create any liability for Our marketplace or our affiliates.<br><br>
 
Member acknowledges and agrees that Our marketplace shall not be required to actively monitor nor exercise any editorial control whatsoever over the content of any message or material or information created, obtained or accessible through the Services or Our marketplace. Our marketplace does not endorse, verify or otherwise certify the contents of any comments or other material or information made by any Member. Each Member is solely responsible for the contents of their communications and may be held legally liable or accountable for the content of their comments or other material or information
Member acknowledges and accepts that each Member is solely responsible for observing applicable laws and regulations in its respective jurisdictions to ensure that all use of the Site and Services are in compliance with the same.<br><br>
Our marketplace reserves the right in our sole discretion to remove, modify or reject any User Content that you submit to, post or display on our marketplace which we reasonably believe is unlawful, violates the Terms, could subject Our marketplace or our affiliates to liability, or is otherwise found inappropriate in Our marketplace’s opinion.<br><br>

If any Member breaches any Terms, or if Our marketplace has reasonable grounds to believe that a Member is in breach of any Terms, Our marketplace can take such actions as it deems appropriate, including without limitation: a.) blocking or deleting the Member’s account and any and all accounts determined to be related to such account by Our marketplace in its discretion; 2.) restricting, downgrading, suspending or terminating the subscription of, access to, or current or future use of any Service; 3.) removing any product listings or other User Content that the Member has submitted, posted or displayed, or imposing restrictions on the number of product listings or User Content that the Member may post or display; 4.) imposing other restrictions on the Member’s use of any features or functions of any Service as Our marketplace may consider appropriate in its sole discretion; <br><br>
These examples may be considered as constituting a violation of the Terms in any of the following circumstances:
- Based upon complaint or claim from any third party, Our marketplace has reasonable grounds to believe that such Member has willfully or materially failed to perform your contract with such third party including without limitation where the Member has failed to deliver any items ordered by such third party after receipt of the purchase price, or where the items Member has delivered materially fail to meet the terms and descriptions outlined in your contract with such third party,
- Our marketplace has reasonable grounds to suspect that any information provided by the Member is not current or complete or is untrue, inaccurate, or misleading, or
- Our marketplace believes that the Member’s actions may cause financial loss or legal liability to Our marketplace or our affiliates or any other Users.<br><br>
 
TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SERVICES PROVIDED BY OUR MARKETPLACE ON OR THROUGH OUR MARKETPLACE ARE PROVIDED "AS IS", "AS AVAILABLE" AND “WITH ALL FAULTS”, AND OUR MARKETPLACE HEREBY EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO, ANY WARRANTIES OF CONDITION, QUALITY, DURABILITY, PERFORMANCE, ACCURACY, RELIABILITY, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. ALL SUCH WARRANTIES, REPRESENTATIONS, CONDITIONS, AND UNDERTAKINGS ARE HEREBY EXCLUDED.
TO THE MAXIMUM EXTENT PERMITTED BY LAW, OUR MARKETPLACE MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE VALIDITY, ACCURACY, CORRECTNESS, RELIABILITY, QUALITY, STABILITY, COMPLETENESS OR CURRENTNESS OF ANY INFORMATION PROVIDED ON OR THROUGH OUR MARKETPLACE; OUR MARKETPLACE DOES NOT REPRESENT OR WARRANT THAT THE MANUFACTURE, IMPORTATION, EXPORT, DISTRIBUTION, OFFER, DISPLAY, PURCHASE, SALE AND/OR USE OF PRODUCTS OR SERVICES OFFERED OR DISPLAYED ON OUR MARKETPLACE DOES NOT VIOLATE ANY THIRD PARTY RIGHTS; AND OUR MARKETPLACE MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND CONCERNING ANY PRODUCT OR SERVICE OFFERED OR DISPLAYED ON OUR MARKETPLACE<br><br>
Our marketplace reserves the right to cooperate fully with governmental authorities, private investigators and/or injured third parties in the investigation of any suspected criminal or civil wrongdoing.  Further, to the extent permitted by applicable laws and policies, Our marketplace may disclose the Member's identity, contact information and/or information regarding the Member's account(s), trades or activities carried out on or via the Site, if requested by a government or law enforcement body, an injured third party, or as a result of a subpoena or other legal action.  Our marketplace shall not be liable for damages or results arising from such disclosure, and Member agrees not to bring any action or claim against Our marketplace for such disclosure.
 <br><br>
Each Member further agrees that Our marketplace is not responsible, and shall have no liability to you or anyone else for any User Content or other material transmitted over our marketplace, including fraudulent, untrue, misleading, inaccurate, defamatory, offensive or illicit material and that the risk of damage from such material rests entirely with each Member. Our marketplace reserves the right, at our own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by the Member, in which event the Member shall cooperate with Our marketplace in asserting any available defenses.<br><br>
Users are solely responsible for all of the terms and conditions of the trades conducted on, through or as a result of use of our marketplace or Services, including, without limitation, terms regarding payment, returns, warranties, shipping, insurance, fees, taxes, title, licenses, fines, permits, handling, transportation and storage.<br><br>

Through our marketplace, Our marketplace provides electronic web-based platforms for exchanging information between buyers and sellers of products and services. Our marketplace does not control and is not liable to or responsible for the quality, safety, lawfulness or availability of the products or services offered for sale on our marketplace or the ability of the sellers to complete a sale or the ability of buyers to complete a purchase.<br><br>
 
Each User acknowledges that it is fully assuming the risks of conducting any purchase and sale trades in connection with using our marketplace or Services, and that it is fully assuming the risks of liability or harm of any kind in connection with subsequent activity of any kind relating to products or services that are the subject of trades using our marketplace. Such risks shall include, but are not limited to, misrepresentation of products and services, fraudulent schemes, unsatisfactory quality, failure to meet specifications, defective or dangerous products, unlawful products, delay or default in delivery or payment, cost miscalculations, breach of warranty, breach of contract and transportation accidents. Such risks also include the risks that the manufacture, importation, export, distribution, offer, display, purchase, sale and/or use of products or services offered or displayed on our marketplace may violate or may be asserted to violate Third Party Rights, and the risk that User may incur costs of defense or other costs in connection with third parties’ assertion of Third Party Rights, or in connection with any claims by any party that they are entitled to defense or indemnification in relation to assertions of rights, demands or claims by Third Party Rights claimants. Such risks also include the risks that consumers, other purchasers, end-users of products or others claiming to have suffered injuries or harms relating to products originally obtained by Users of our marketplace as a result of purchase and sale trades in connection with using our marketplace may suffer harms and/or assert claims arising from their use of such products. All of the foregoing risks are hereafter referred to as "Trade Risks". Each User agrees that Our marketplace shall not be liable or responsible for any damages, claims, liabilities, costs, harms, inconveniences, business disruptions or expenditures of any kind that may arise a result of or in connection with any Trade Risks.
In the event that any User has a dispute with any party to a trade, such User agrees to release and indemnify Our marketplace (and our agents, affiliates, directors, officers and employees) from all claims, demands, actions, proceedings, costs, expenses and damages (including without limitation any actual, special, incidental or consequential damages) arising out of or in connection with such trade.<br><br>

Each User hereby agrees to indemnify and hold Our marketplace, our affiliates, directors, officers and employees harmless, from any and all losses, claims, liabilities (including legal costs on a full indemnity basis) which may arise from such User's use of our marketplace or Services (including but not limited to the display of such User's information on our marketplace) or from your breach of any of the terms and conditions of the Terms. Each User hereby further agrees to indemnify and hold Our marketplace, our affiliates, directors, officers and employees harmless, from any and all losses, damages, claims, liabilities (including legal costs on a full indemnity basis) which may arise from User's breach of any representations and warranties made by User to Our marketplace. Each User hereby further agrees to indemnify and save Our marketplace, our affiliates, directors, officers and employees harmless, from any and all losses, damages, claims, liabilities (including legal costs on a full indemnity basis) which may arise, directly or indirectly, as a result of any claims asserted by Third Party Rights claimants or other third parties relating to products offered or displayed on our marketplace. Each User hereby further agrees that Our marketplace is not responsible and shall have no liability to you, for any material posted by others, including defamatory, offensive or illicit material and that the risk of damages from such material rests entirely with each User. Our marketplace reserves the right, at our own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, in which event you shall cooperate with Our marketplace in asserting any available defenses.<br><br>
 
Our marketplace shall not be liable for any special, direct, indirect, punitive, incidental or consequential damages or any damages whatsoever (including but not limited to damages for loss of profits or savings, business interruption, loss of information), whether in contract, negligence, tort, equity or otherwise or any other damages resulting from any of the following: the use or the inability to use our marketplace or Services; any defect in goods, samples, data, information or services purchased or obtained from a User or any other third party through our marketplace; violation of Third Party Rights or claims or demands that User's manufacture, importation, export, distribution, offer, display, purchase, sale and/or use of products or services offered or displayed on our marketplace may violate or may be asserted to violate Third Party Rights; or claims by any party that they are entitled to defense or indemnification in relation to assertions of rights, demands or claims by Third Party Rights claimants; unauthorized access by third parties to data or private information of any User; statements or conduct of any User of our marketplace; or; any matters relating to Services however arising, including negligence.<br><br>
 
Notwithstanding any of the foregoing provisions, the aggregate liability of Our marketplace, our employees, agents, affiliates, representatives or anyone acting on our behalf with respect to each User for all claims arising from the use of our marketplace or Services during any calendar year shall be limited to the greater of (a) the amount of fees the User has paid to Our marketplace or our affiliates during the calendar year and (b) the maximum amount permitted in the applicable law. The preceding sentence shall not preclude the requirement by the User to prove actual damages. All claims arising from the use of our marketplace or Services must be filed within one (1) year from the date the cause of action arose or such longer period as prescribed under any applicable law governing this Term of Use..
The limitations and exclusions of liability to you under the Terms shall apply to the maximum extent permitted by law and shall apply whether or not Our marketplace has been advised of or should have been aware of the possibility of any such losses arising.<br><br>
Force Majeure: Under no circumstances shall Our marketplace be held liable for any delay or failure or disruption of the content or services delivered through our marketplace resulting directly or indirectly from acts of nature, forces or causes beyond our reasonable control, including without limitation, Internet failures, computer, telecommunications or any other equipment failures, electrical power failures, strikes, labor disputes, riots, insurrections, civil disturbances, shortages of labor or materials, fires, flood, storms, explosions, war, governmental actions, orders of domestic or foreign courts or tribunals or non-performance of third parties.<br><br>
You agree that all agreements, notices, demands, disclosures and other communications that Our marketplace sends to you electronically satisfy the legal requirement that such communication should be in writing.<br><br>
Subject to any Additional Agreements, the Terms constitute the entire agreement between you and Our marketplace with respect to and govern your use of our marketplace and Services, superseding any prior written or oral agreements in relation to the same subject matter herein. Our marketplace and you are independent contractors, and no agency, partnership, joint venture, employee-employer or franchiser-franchisee relationship is intended or created by the Terms. Our marketplace shall have the right to assign the Terms (including all of our rights, titles, benefits, interests, and obligations and duties in the Terms to any person or entity (including any affiliates of Our marketplace). You may not assign, in whole or part, the Terms to any person or entity.<br><br>

The Terms shall be governed by the laws of the Cayman Islands only, without regard to its conflict of law provisions and the parties to the Terms agree to submit to the exclusive jurisdiction of the courts of the Cayman Islands.  <br><br>
This Privacy Policy is valid for all products and services provided by us and sets out how we collect, use and disclose information in relation to users of our marketplace.  
Information including user name, address, phone number, and email address, crypto wallet address from which you will be paying our services from, will be collected at the time of user registration on our marketplace. We record details of users’ activities on our marketplace. Information relating to such trades (including, but not limited to, the types and specifications of the goods, pricing and delivery information, any dispute records and any information disclosed in any discussion forum)  may be collected. We record users' buying and browsing activities on our platform including but not limited to IP addresses, browsing patterns, buyer behavioral patterns and equipment information. In addition, we gather statistical information about our marketplace and visitors to our marketplace including, but not limited to, IP addresses, browser software, operating system, software and hardware attributes, pages viewed, number of sessions and unique visitors.<br><br>
Our marketplace may collect, process and use your Personal Data for the these purposes:<br><br>
Verifying your identity; processing your registration as a user, providing you with a log-in for our marketplace and maintaining and managing your registration; facilitating communication between buyers and sellers on our marketplace, <br><br>
When we believe it is necessary to comply with applicable laws or to exercise, establish or defend our legal rights or protect your vital interests or those of any other person, we may also disclose and transfer your Personal Data to our professional advisers, law enforcement agencies, insurers, government and regulatory and other organizations, or as otherwise required or permitted by applicable laws.<br><br>
We may disclose your Personal Data to an actual or potential buyer (and its agents and advisers) in connection with any actual or proposed purchase, merger or acquisition of any part of our business, provided that we inform the buyer it must use your Personal Data only for the purposes disclosed in this Privacy Policy.<br><br>
We retain your Personal Data as long as we have an ongoing legitimate business need to do so for example to provide services or products to you, or as required or permitted by applicable laws, such as tax and accounting laws. <br><br>
Rights considering personal user data: Under the applicable laws, you may have the rights of access to Personal Data held by us and other rights.  <br><br>
If and to the extent permitted by applicable law, we may charge you a fee for the processing of any request you make regarding your Personal Data.<br><br>
We use "cookies" to store specific information about you and track your visits to our marketplace, either through a compute or via a mobile device. You have the right to decide whether to accept or reject cookies. If you choose to set your web browser controls to reject cookies. <br><br>
Our marketplace and their contents are not targeted to minors (those under the age of 18) and we do not intend to sell any of our products or services to minors. 
Any changes to this Privacy Policy will be communicated by us posting an amended Privacy Policy on our marketplace. Once posted on our marketplace, the new Privacy Policy will be effective immediately. <br><br>
For marketplace visitors from the European Union: This section of the Privacy Policy applies only if you use our marketplace or services covered by this Privacy Policy from a country that is a Member State of the European Union, and supplements the information in this Privacy Policy.<br><br>
We process Personal Data for the purposes set out in this Privacy Policy, as described above. Our legal basis to process Personal Data will depend on the Personal Data concerned and the specific context in which we collect it. However, we will normally collect and process Personal Data about you only where it is: necessary for the performance of any contract between you and Our marketplace (for example, to provide you with the services you request and to identify and authenticate you so you may use our marketplace); necessary to comply with legal requirements (for example, to comply with applicable accounting rules and to make mandatory disclosures to law enforcement); necessary for our legitimate interests and not overridden by your rights; and/or where it is based on your consent.<br><br>
If we collect and use your Personal Data in reliance on our legitimate interests), this interest will normally be to operate our marketplace and services, manage our relationship with you and communicate with you as necessary to provide our services to you and for our legitimate commercial interest, for instance, when responding to your queries, improving our Our marketplace and our services, undertaking marketing, or for the purposes of ensuring the security of our Our marketplace and services and detecting or preventing illegal activities such as fraud. <br><br>
If we ask you to provide Personal Data to comply with a legal requirement or to enter into a contract with you, we will make this clear at the relevant time and advise you whether the provision of your Personal Data is mandatory or not (as well as of the possible consequences if you do not provide your Personal Data). In some instances, you may be required to provide us with Personal Data for processing as described above, in order for us to be able to provide you all of our services, and for you to use all the features of our Our marketplace.<br><br>
We retain your Personal Data as long as we have an ongoing legitimate business need to do so for example to provide services or products to you, or as required or permitted by applicable laws, such as tax and accounting laws. When we have no ongoing legitimate business need to process your Personal Data, we will either delete or anonymise it or, if this is not possible (for example, because your Personal Data has been stored in backup archives), then we will securely store your Personal Data and isolate it from any further processing until deletion is possible.<br><br>
Our business may require us to transfer your Personal Data to countries outside of the European Economic Area (“EEA”), including to countries that may not provide the same level of data protection as your home country such as the United States. <br><br>
If you are a resident of the European Economic Area, you have the following data protection rights, which you can exercise at any time by contacting us using the contact details provided under section on the bottom of our landing page:
•      The right to access, correct, update or request deletion of your personal data. 
•      The right to object to processing of your personal information when it is based on our legitimate interests, and separately the right to object to direct marketing.
•      The right to ask us, in some situations, to restrict processing of your personal information or request portability of your personal information.
•      The right to opt-out of marketing communications we send you at any time. 

•      If we have collected and process your personal information with your consent, then you have the right to withdraw your consent at any time. Withdrawing your consent will not affect the lawfulness of any processing we conducted prior to your withdrawal, nor will it affect processing of your personal information conducted in reliance on lawful processing grounds other than consent.
•      The right to complain to a data protection authority about our collection and use of your personal information. For more information, please contact your local data protection authority.<br><br>
We respond to all requests we receive from individuals wishing to exercise their data protection rights in accordance with applicable data protection laws. If you are aware of changes or inaccuracies in your information, you should inform us of such changes so that our records may be updated or corrected.
 
 <br><br><br><br>





            </div>
        </div>
    </div>
</div>
