version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: demblock-login-sql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - .:/app/db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=.password
      - MYSQL_DATABASE=my_db
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=.mypwd
    networks:
      - demblock_login
    ports:
      - "8082:3306"
  website:
    container_name: demblock-login-app
    build:
      context: ./
    volumes:
      - .:/app/web
    networks:
      - demblock_login
    ports:
      - 8000:3030
    depends_on:
      - mysql
networks:
  demblock_login: