# Default values for demblock.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## =================================================================
## Services configuration
##

image:
  registry: eu.gcr.io
  repository: demblock/demblock
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: 
    name: pull-docker-creds

# PostgreSQL configuration

db:
  username:
  password:
  host:
  database:

# SMTP mailer configuration

smtp:
  host: 
  port: 
  username: 
  password: 

# Services configuration

network:
  serviceType: NodePort
  globalIP: demblock-global-ip
  healthPort: 21080
  frontend:
    name: demblock.com
    port: 21080
    tls: true
    certManager: false
  backend:
    name: backend.demblock.com
    port: 20080
    tls: true
    certManager: false

## =================================================================

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
replicaCount: 1
resources:
  requests:
    memory: 512Mi
    cpu: 300m
