# Default values for demblock.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# =================================================================
# =========  Services configuration
# Defaults:
#     registry/eu.gcr.io - created by demblock infrastructure pipeline
#     repository/demblock/demblock - created by demblock infrastructure pipeline
#     pullSecrets/pull-docker-creds - created by demblock infrastructure pipeline (delete to disable)
image:
  registry   : eu.gcr.io
  repository : demblock/demblock
  tag        : 
  pullPolicy : IfNotPresent
  pullSecrets: 
    name: pull-docker-creds

# ========= PostgreSQL configuration
# Defaults:
#     secret/db-data - created by demblock infrastructure pipeline
db:
  secret  : db-data
  host    : 
  database: 

# ========= SMTP mailer configuration
# Defaults:
#     secret/smtp-data - created by demblock infrastructure pipeline
smtp:
  host  : 
  port  : 
  secret: smtp-data

# ========= Services configuration
# Defaults:
#     globalIP/demblock-global-ip - created by demblock infrastructure pipeline
#     managedCert - created by demblock infrastructure pipeline
network:
  serviceType: NodePort
  frontend:
    name: demblock.com
    port: 21080
  backend:
    name: backend.demblock.com
    port: 20080

## =================================================================
## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
replicaCount: 1
resources:
  requests:
    memory: 150Mi
    cpu: 100m
tolerations:
  - effect: NoSchedule
    key: task
    operator: Equal
    value: preemptive
