apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "name" . }}
      release: "{{ .Release.Name }}"
  serviceName: {{ template "name" . }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
    spec:
      initContainers:
        - name: init-db
          image: {{ template "repo.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command: ["php", "yii", "migrate", "--interactive=0"]
          env:
            - name: MYSQL_USER
              value: {{ .Values.db.username | quote }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.db.password }}
            - name: MYSQL_HOST
              value: {{ .Values.db.host }}
            - name: MYSQL_DATABASE
              value: {{ .Values.db.database }}
      containers:
        - name: yii-apache
          image: {{ template "repo.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          ports:
          {{- range .Values.network.hosts }}
            - containerPort: {{ .port }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /site/prijava
              port: {{ .Values.network.healthPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /site/prijava
              port: {{ .Values.network.healthPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: MYSQL_USER
              value: {{ default "root"  .Values.db.username | quote }}
            - name: MYSQL_PASSWORD
              value: {{ default ""  .Values.db.password | quote }}
            - name: MYSQL_HOST
              value: {{ default "localhost"  .Values.db.host }}
            - name: MYSQL_DATABASE
              value: {{ .Values.db.database }}
            - name: MAILER_HOST
              value: {{ .Values.smtp.host }}
            - name: MAILER_PORT
              value: {{ .Values.smtp.port }}
            - name: MAILER_USERNAME
              value: {{ .Values.smtp.username }}
            - name: MAILER_PASSWORD
              value: {{ .Values.smtp.password }}
          volumeMounts:
            - name: storage-pv
              mountPath: /app/frontend/web/uploads
              subPath: frontend/web/uploads
          resources:
{{ toYaml .Values.resources | indent 12 }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecrets.name | quote }}
      {{ end }}
  volumeClaimTemplates:
  - metadata:
      name: storage-pv
    spec:
      accessModes: 
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi