apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    kubernetes.io/ingress.class: gce
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.network.globaIP | quote }}
spec:
  rules:
    {{- range .Values.network.hosts }}
    - host: {{ .name }}
      http:
        paths:
        - path: {{ default "/" .path }}
          backend:
            serviceName: {{ .type }}
            servicePort: {{ .port }}
    {{- end }}
  tls:
  - hosts:
    {{- range .Values.network.hosts }}
    - {{ .name }}
    {{- end }}
    secretName: {{ template "name" . }}-certs
