apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    # networking.gke.io/managed-certificates: "{{ .Values.network.frontend.cert }},{{ .Values.network.backend.cert }}"
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.network.globalIP | quote }}
    cert-manager.io/cluster-issuer: letsencrypt-staging
    acme.cert-manager.io/http01-edit-in-place: "true"
    
    # ingress.gcp.kubernetes.io/pre-shared-cert: {{ .Values.network.certName | quote }}
spec:
  rules:
    - host: {{ .Values.network.frontend.name }}
      http:
        paths:
        - backend:
            serviceName: {{ template "name" . }}
            servicePort: {{ .Values.network.frontend.port }}
    - host: {{ .Values.network.backend.name }}
      http:
        paths:
        - backend:
            serviceName: {{ template "name" . }}
            servicePort: {{ .Values.network.backend.port }}
  tls:
  - secretName: demblock-certs
    hosts:
    - {{ .Values.network.frontend.name }}
    - {{ .Values.network.backend.name }}