apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    #kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.network.globalIP | quote }}
    #cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    {{- range .Values.network.hosts }}
    - host: {{ .name }}
      http:
        paths:
        - backend:
            serviceName: {{ template "name" $ }}
            servicePort: {{ .port }}
    {{- end }}
  #tls:
  #- hosts:
  #  {{- range .Values.network.hosts }}
  #  - {{ .name }}
  #  {{- end }}
  #  secretName: {{ template "name" . }}-certs
