apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.network.globalIP | quote }}
    networking.gke.io/managed-certificates: {{ .Values.network.certName | quote }}
    kubernetes.io/ingress.class: gce
    cert-manager.io/acme-challenge-type: http01
    cert-manager.io/acme-http01-edit-in-place: true
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  rules:
    - host: {{ .Values.network.frontend.name }}
      http:
        paths:
        - backend:
            serviceName: {{ template "name" . }}
            servicePort: {{ .Values.network.frontend.port }}
    - host: {{ .Values.network.backend.name }}
      http:
        paths:
        - backend:
            serviceName: {{ template "name" . }}
            servicePort: {{ .Values.network.backend.port }}
  tls:
  - hosts:
    {{- range .Values.network.hosts }}
    - {{ .name }}
    {{- end }}
    secretName: {{ template "name" . }}-certs
