{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.globaIP }}
spec:
  rules:
{{- range .Values.ingress.hosts }}
    - host: {{ .name }}
      http:
        paths:
        - path: {{ default "/" .path }}
          backend:
            serviceName: {{ template "name" . }}
            servicePort: {{ .port }}
{{- end }}
  tls:
  - hosts:
{{- range .Values.ingress.hosts }}
    - {{ .name }}
{{- end }}
    secretName: {{ template "name" . }}-certs
{{- end }}
