apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.network.serviceType }}
  loadBalancerIP: {{ .Values.network.globalIP }}
  externalTrafficPolicy: Local
  selector:
    app: {{ template "name" . }}
  ports:
{{- range .Values.network.hosts }}
    - name: {{ .type }}
      port: {{ .port }}
      targetPort: {{ .port }}
{{- end }}
