apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.network.serviceType }}
  #loadBalancerIP: {{ .Values.network.globalIP }}
  #externalTrafficPolicy: Local
  selector:
    app: {{ template "name" . }}
  ports:
    - name: {{ template "name" . }}-frontend
      port: {{ .Values.network.frontend.port }}
      targetPort: {{ .Values.network.frontend.port }}
    - name: {{ template "name" . }}-backend
      port: {{ .Values.network.backend.port }}
      targetPort: {{ .Values.network.backend.port }}
