apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.serviceType }}
  loadBalancerIP: {{ .Values.globalIP }}
  #{{- if (or (eq .Values.serviceType "LoadBalancer") (eq .Values.serviceType "NodePort")) }}
  #externalTrafficPolicy: {{ .Values.serviceExternalTrafficPolicy | quote }}
  #{{- end }}
  selector:
    app: {{ template "name" . }}
  ports:
    - name: frontend-http
      port: {{ .Values.ports.frontend }}
      targetPort: {{ .Values.ports.frontend }}
    - name: backend-http
      port: {{ .Values.ports.backend }}
      targetPort: {{ .Values.ports.backend }}
