name: Pipeline - Build PR
on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: 'CI - Build PR image'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry - PR
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: https://eu.gcr.io/demblock/demblock
        tags: pr
        tag_with_sha: true
