name: Build
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: HurricanKai/Publish-Docker-Github-Action@master
      with:
        name: demblock/demblock
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: eu.gcr.io
        tagging: true
        cache: true
