name: CI/CD Pipeline
on:
  # Run on pushed version
  push:
    tags:
    - '*'

# ========================================================
env:
  # Project shared
  GCP_PROJECT   : demblock
  ARTIFACT_NAME : demblock
  DB_DATABASE   : demblock
  HELM_APP      : demblock
  HELM_NAMESPACE: default
  GKE_CLUSTER   : ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE      : ${{ secrets.GKE_ZONE }}
  DB_HOST       : ${{ secrets.DB_HOST }}
  SMTP_HOST     : ${{ secrets.SMTP_HOST }}
  SMTP_PORT     : ${{ secrets.SMTP_PORT }}

  # Consts
  CHART_PATH: "./k8s"
  KUBECONFIG: ./kube/config

  #### Also required:
  # GOOGLE_SA_EMAIL
  # GOOGLE_SA_KEY
  # GIT_AUTH_TOKEN

jobs:
  # ========================================================
  # ============= CI WORKFLOW
  # ========================================================
  ci:
    name: 'Build artifacts'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
  
    - name: Push to Registry [tagged]
      uses: mr-smithers-excellent/docker-build-push@v2
      with:
        image   : ${{ env.GCP_PROJECT }}/${{ env.ARTIFACT_NAME }}
        registry: eu.gcr.io
        username: _json_key
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Push to Registry [latest]
      uses: mr-smithers-excellent/docker-build-push@v2
      with:
        image   : ${{ env.GCP_PROJECT }}/${{ env.ARTIFACT_NAME }}
        tag     : latest
        registry: eu.gcr.io
        username: _json_key
        password: ${{ secrets.DOCKER_PASSWORD }}

  # ========================================================
  # ============= CD WORKFLOW
  # ========================================================
  cd:
    name: 'Deploy artifacts'
    needs: ci
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Versioning configuration
    - name: CD - Get version
      uses: anothrNick/github-tag-action@1.17.2
      id: tagName
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_AUTH_TOKEN }}
        WITH_V      : true
        DRY_RUN     : true

    - name: CD - Set version
      run: |
        echo ::set-env name=RELEASE_VERSION::${{ steps.tagName.outputs.tag }}
        echo $RELEASE_VERSION

    # Setup gcloud CLI
    - name: CD - GCP Auth
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '286.0.0'
        service_account_email: ${{ secrets.GOOGLE_SA_EMAIL }}
        service_account_key: ${{ secrets.GOOGLE_SA_KEY }}
        project_id: ${{ env.GCP_PROJECT }}

    # Get GKE credentials
    - name: CD - GKE Auth
      run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

    - name: Helm - Install dependencies
      run: |
        pip3 install --upgrade setuptools pip
        pip3 install -r ./.cicd/requirements.txt

    # Update chart
    - name: Helm - Update chart
      run: |
        python3 ./.cicd/update_chart.py
        cat ./k8s/values.yaml

    # Lint chart
    - name: Helm - Lint
      run: |
        helm lint ./k8s/

    # Upload artifact
    - uses: actions/upload-artifact@v1
      name: Helm - Upload artifact
      with:
        name: ${{ env.HELM_APP }}-${{ env.RELEASE_VERSION }}
        path: ./k8s/
        
    # Deploy chart
    - name: Helm - Deploy chart
      run: |
        helm upgrade $HELM_APP $CHART_PATH/ --install --wait --timeout 15m0s --atomic --namespace=$HELM_NAMESPACE --values=$CHART_PATH/values.yaml
