name: CD
on:
  schedule:
    - cron:  '* * * * *'
jobs:
  build:
    name: 'Deployment'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Get version
      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF##*/v}
    - name: Print version
      run: echo $RELEASE_VERSION
